### ISSUE TITLE
Layouts Codelab text references HorizontalScroller

### ISSUE THREAD

**Issue by jasonostrander** [googlecodelabs/android-compose-codelabs#1]
Not an issue with the code, but rather the CodeLab text. Specifically the section on implementing the StaggeredGrid: https://codelabs.developers.google.com/codelabs/jetpack-compose-layouts/index.html?index=..%2F..index#6

It references `HorizontalScroller`. I believe this should now be `ScrollableRow`.

**Comment by sjcqs** [comment]
In the same vein, 
```
Layout(
        modifier = modifier,
        children = children
    ) { measurables, constraints, layoutDirection ->
// ...
}
```

`layoutDirection` seems to have been moved from `MeasureBlock` lambda to `androidx.compose.ui.MeasureScope`

**Comment by manuelvicnt** [comment]
Thanks for reporting! Already fixed both issues that should be available soon
