### ISSUE TITLE
Missing text style customization - Theming Codelab - Step 8

### ISSUE THREAD

**Issue by peterMonteer** [googlecodelabs/android-compose-codelabs#125]
No text style customization is made in this code snippet

![Captura de ecrã 2021-03-07, às 12 08 04](https://user-images.githubusercontent.com/28009502/110239273-009e3400-7f3e-11eb-817b-80adba4c9a2a.png)

**Comment by nickbutcher** [comment]
Thanks for the report. I've fixed this internally and it will be released in our next update.
