### ISSUE TITLE
[StateCodelab] Final result not working as intended

### ISSUE THREAD

**Issue by CoreFloDev** [googlecodelabs/android-compose-codelabs#126]
Hi,

I have done the state codelab last weekend and the final result isn't working as intended. When you try to edit a todo, it doesn't let you change the todo task name, only one letter can be changed as displayed in the video. I believe that's mostly because it doesn't implement a unidirectional data flow as there is two separates states, one for the todo list and one for the edit state. But it also could be only a compose issue that I don't understand.

To reproduce, I have executed the app on a real device and I have tried both the final module and doing the tutorial step by step it happens either case

https://user-images.githubusercontent.com/1541410/110326687-e719ec80-8010-11eb-93c5-4e3c3de48110.mp4

Please let me know if you need more info, I am very interested by your solution
Flo

**Comment by bupont** [comment]
There was an error under Step 11 "Use the inline editor in LazyColumn" where the lambdas for onEditItemChange and onEditDone were surrounded by brackets but this seems to have been fixed.

**Comment by CoreFloDev** [comment]
Hi Bupont,

I just checked the code I am using and there is no brackets around the code you mentioned. Did you managed by any chances to reproduce the issue on your side?

Thanks,
Flo

**Comment by CoreFloDev** [comment]
I investigated a little bit more, the issue seems to come from the Samsung keyboard. I have tried on a different physical device and it was working fine. I also tried on that same device using the google keyboard and it was fine.
