### ISSUE TITLE
[StateCodelab] Step 12 - Crash when removing edited item

### ISSUE THREAD

**Issue by bupont** [googlecodelabs/android-compose-codelabs#127]
Steps to reproduce:
1. Add item
2. Edit item
3. Press remove
4. Crash

Stacktrace:

> 2021-03-08 15:06:57.750 14280-14280/com.example.statecodelab E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.statecodelab, PID: 14280
>     java.lang.ArrayIndexOutOfBoundsException: length=8030; index=-2
>         at androidx.compose.runtime.SlotTableKt.groupSize(SlotTable.kt:2558)
>         at androidx.compose.runtime.SlotTableKt.access$groupSize(SlotTable.kt:1)
>         at androidx.compose.runtime.SlotReader.groupSize(SlotTable.kt:596)
>         at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2215)
>         at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2499)
>         at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2625)
>         at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:406)
>         at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:724)
>         at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:100)
>         at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:437)
>         at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:411)
>         at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
>         at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:112)
>         at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:43)
>         at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:72)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:796)
>         at android.view.Choreographer.doFrame(Choreographer.java:727)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
>         at android.os.Handler.handleCallback(Handler.java:938)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.app.ActivityThread.main(ActivityThread.java:7656)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by astamato** [comment]
Thank you for flagging this issue! We've replaced the first version of the StateCodelab (Todo app), hence this issue is obsolete.
