### ISSUE TITLE
[StateCodelab] Not Found Class in Step 7 - Dynamic UI based on state

### ISSUE THREAD

**Issue by CherryLover** [googlecodelabs/android-compose-codelabs#136]
![image](https://user-images.githubusercontent.com/18376501/110742390-3a8a7580-8271-11eb-9210-206e20ebdb51.png)

**Comment by CherryLover** [comment]
After I change compose version to beta02, some method is not found in Todo Components.kt file.

**Comment by florina-muntenescu** [comment]
Thanks for reporting. The codelab currently uses beta02 and Github actions pass successfully.
