### ISSUE TITLE
[LayoutsCodelab]Unable to determine application id: com.android.tools.idea.run.ApkProvisionException

### ISSUE THREAD

**Issue by CrazyPumPkin** [googlecodelabs/android-compose-codelabs#148]
Click 'run app' and show 'Unable to determine application id: com.android.tools.idea.run.ApkProvisionException'

**Comment by CrazyPumPkin** [comment]
Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: Error loading build artifacts from

**Comment by CrazyPumPkin** [comment]
Seems there are some issues about incompatibility in the project config.
I change the config to a workable one as below:
Gradle -> 6.8.2
compose -> 1.0.0-beta01
Gradle plugin -> 7.0.0-alpha08
Kotlin -> 1.4.30

**Comment by DavidMendozaMartinez** [comment]
@CrazyPumPkin I've had the same error with MigrationCodelab and it's fixed by updating the canary of Android Studio Arctic Fox to the latest version (right now: Android Studio Arctic Fox | 2020.3.1 Canary 14).
I hope it helps you!

**Comment by CrazyPumPkin** [comment]
@DavidMendozaMartinez Work fine on Canary14!  lol
