### ISSUE TITLE
doesn't click

### ISSUE THREAD

**Issue by Pont14c** [googlecodelabs/android-compose-codelabs#165]
https://github.com/googlecodelabs/android-compose-codelabs/blob/398ad6d38a176cb342f27e60f31bdd021f19c09e/AnimationCodelab/finished/src/main/java/com/example/android/codelab/animation/ui/home/Home.kt#L385
I fixed it with @ExperimentalMaterialApi annotation

**Comment by yaraki** [comment]
Fixed by #167
