### ISSUE TITLE
swipe doesn't work on modifier 

### ISSUE THREAD

**Issue by Pont14c** [googlecodelabs/android-compose-codelabs#166]
https://github.com/googlecodelabs/android-compose-codelabs/blob/398ad6d38a176cb342f27e60f31bdd021f19c09e/AnimationCodelab/finished/src/main/java/com/example/android/codelab/animation/ui/home/Home.kt#L646
probably due to the new version of compose or smth else
 I moved "swipeToDismiss" to modifier from Row in the same method, but it doesn't work properly, although swipe is working now.
Could you please help me to figure out, what is wrong?

**Comment by MadFlasheroo7** [comment]
since compose is in beta many libraries in experimental, so make sure u r compose is on the latest version **1.0.0-beta08** (as of commenting) and to fix it annotate ```swipeToDismiss``` function with ```@ExperimentalAnimationApi``` annotation
