### ISSUE TITLE
[BasicsCodelab] How to make list visible in preview for Basics Codelab

### ISSUE THREAD

**Issue by alvindizon** [googlecodelabs/android-compose-codelabs#228]
In the Basics Codelab, there's an [image](https://developer.android.com/codelabs/jetpack-compose-basics/img/8a54a386b258277a.png) in Part 12 showing a preview of the list alongside the Onboarding screen preview. I'm wondering how `DefaultPreview` can be made to display the list if it can only be shown once the continue button is clicked? Here's how the preview looks on my end:

![image](https://user-images.githubusercontent.com/30955662/148624255-51b4a0f6-615e-4d4b-9da3-5df08d4b8b29.png)

**Comment by JolandaVerhoef** [comment]
Sorry for the late response, this issue slipped through the cracks. If you look at the code at the bottom of https://developer.android.com/codelabs/jetpack-compose-basics#7 you'll see that the second preview actually directly calls `Greetings`. The onboarding logic is not part of that composable. So your Preview should directly show the list. If stuck, you can try to replace your code by the code at the end of step 8.
