### ISSUE TITLE
[NavigationCodelab] _viaUI Tests fail

### ISSUE THREAD

**Issue by suau** [googlecodelabs/android-compose-codelabs#229]
Hi,
I just went through the codelab and couldn't figure out on my own why the _viaUI Tests would not work, I then switched over to the `end` branch to discover the tests there also fail.
Watching the emulator during the test and commenting them out one by one, I saw `_callingNavigate` test to actually change the screen, but the `_viaUI` tests don't. Any ideas ? Is this working for anyone ?

**Comment by simona-anomis** [comment]
Hi, thanks for reporting, but I'm unable to reproduce this issue.

**Comment by suau** [comment]
working now as of 4f0105f3d65f7386782fac6c1669c31968041edb
