### ISSUE TITLE
[AccessibilityCodelab] How to show toast containing text that Talkback reads?

### ISSUE THREAD

**Issue by alvindizon** [googlecodelabs/android-compose-codelabs#230]
in Part 4 of the Accessibility Codelab, there is a GIF that shows what looks like a Toast containing text that Talkback also [reads](https://developer.android.com/codelabs/jetpack-compose-accessibility/img/e4aea6991ba119c0.gif). How do you enable that?

**Comment by JolandaVerhoef** [comment]
I turned it on in Talkback > Settings > Advanced Settings > Developer Settings > Display speech output

The exact place might be different depending on your OEM and version of Talkback
