### ISSUE TITLE
Final preview is not same in main branch, end branch and in preview in Codelab.

### ISSUE THREAD

**Issue by pawankhandal52** [googlecodelabs/android-compose-codelabs#283]
After following the code lab  final output is not same. Font Size / Font weight  issue in current source code.
Image from Code Lab
![24ff9efa75f22198](https://user-images.githubusercontent.com/16113573/188633635-90c1d06f-5097-4015-989d-3917379d42c8.png)
Image After completion of Codelab
![Screenshot_20220906_175207](https://user-images.githubusercontent.com/16113573/188633824-e2a2e185-dcf4-4889-b181-cc7a954b790a.png)

How to fix this.

**Comment by JolandaVerhoef** [comment]
It looks like you didn't wrap your preview into the MySootheTheme theme composable. Please check out the end branch of the code to see the final result. I'll close this issue now, but feel free to re-open if there's still an issue!
