### ISSUE TITLE
Layouts Codelab "rounded corner ripple"

### ISSUE THREAD

**Issue by ColtonIdle** [googlecodelabs/android-compose-codelabs#3]
In the Layout Codelab I don't get this part

> For example, if you wanted to add some outer spacing, change the background color of the composable, and round the corners of the ripple, you could use the following code:

specifically the "round the corners of the ripple". This is the code snippet they're talking about:
```
    Row(modifier
        .padding(8.dp)
        .clip(RoundedCornerShape(4.dp))
        .background(MaterialTheme.colors.surface)
        .clickable(onClick = { /* Ignoring onClick */ })
        .padding(16.dp)
    ) {
```
We're not actually rounding the corner of the ripple, we're more so rounding the corner of the row, and so the ripple only goes up to the clipped area which gives you a rounded corner ripple... right?

**Comment by manuelvicnt** [comment]
Thanks for reporting! Already fixed this and should be available soon
