### ISSUE TITLE
How should card components and attributes be imported?

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [googlecodelabs/android-compose-codelabs#312]
![image](https://user-images.githubusercontent.com/54784104/205002400-0182db00-66db-4e55-9c11-21f9a4c881f7.png)
![image](https://user-images.githubusercontent.com/54784104/205002755-4a53bed8-dc7c-46d3-9553-fe8c8195e0b8.png)
![image](https://user-images.githubusercontent.com/54784104/205002821-4b468311-1914-45e4-a906-a29e62343f06.png)
![image](https://user-images.githubusercontent.com/54784104/205003004-e296633c-d7a9-4c96-8357-ca80009934ce.png)

**Comment by SaltedFish-Extreme** [comment]
Well, I found that upgrading all the packages introduced in the project to the latest version will have Card components and properties, but the corresponding compilation SDK needs to be upgraded to 33, and the minimum adaptation SDK needs to be 25

**Comment by ppjjhh** [comment]
me too. same issue.

**Comment by ppjjhh** [comment]
add these sentences to gradle's dependencies, and the Card will be found. 

def composeBom = platform('androidx.compose:compose-bom:2022.10.00')
implementation(composeBom)
androidTestImplementation(composeBom)

**Comment by SaltedFish-Extreme** [comment]
@ppjjhh thanks，I later upgrade the relevant dependent libraries to the latest version and it can be used

![image](https://user-images.githubusercontent.com/54784104/205535709-39bd5f4c-817c-4a7c-970f-fb701b915eb7.png)
