### ISSUE TITLE
[BasicLayoutsCodelab] only render AlignYourBodyRow when executing on emulator or physical device

### ISSUE THREAD

**Issue by miguelangelss4** [googlecodelabs/android-compose-codelabs#313]
Cloned git repo, and **"end" branch** checkedout. But the project does not work, it only renders AlignYourBodyRow function. Previews are working fine.
![image](https://user-images.githubusercontent.com/15887424/209431554-a691191b-f4a7-44dc-8e9d-5336221b1efe.png)
Emultaor: default pixel 3a with API 33

**Comment by osirvics** [comment]
I am having the same issue, any solution for this?

**Comment by osirvics** [comment]
Fixed, ensure you are building and deploying "app" instead of "AlignYourBodyRow"

**Comment by miguelangelss4** [comment]
> Fixed, ensure you are building and deploying "app" instead of "AlignYourBodyRow"

that was my mistake. Thanks!
