### ISSUE TITLE
Layout Codelab, Step 5, link to Scaffold

### ISSUE THREAD

**Issue by ColtonIdle** [googlecodelabs/android-compose-codelabs#4]
https://developer.android.com/codelabs/jetpack-compose-layouts?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fcompose%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fjetpack-compose-layouts#4

Step 5

"Compose comes with built-in Material Component composables that you can use to create your app. The most high-level composable is Scaffold."

Scaffold is a link that takes you here https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:ui/ui-material/src/main/java/androidx/ui/material/Scaffold.kt

When you go there it says

> The file does not exist at this commit
> The file you have selected did not exist at this point in history. It was deleted in commit fdf0807. 
>

**Comment by manuelvicnt** [comment]
Thanks for reporting! Already fixed this and should be available soon
