### ISSUE TITLE
Update 'Basics' end for 1.0.0-alpha06

### ISSUE THREAD

**Issue by chrisbanes** [googlecodelabs/android-compose-codelabs#40]
Should be merged into `dev_alpha06_end`

**Comment by yrezgui** [comment]
The code would the same as in the `main` branch as we're starting the codelab on an empty project compared to the migration codelab, is that ok?

**Comment by yrezgui** [comment]
I made #43 to use the alpha 06 release (and not the snapshot), targeting `dev_alpha06_main`.
Tell me if you need the same for `dev_alpha06_end`
