### ISSUE TITLE
Typo in StateCodelab part 8

### ISSUE THREAD

**Issue by itsandreramon** [googlecodelabs/android-compose-codelabs#5]
At the bottom of the code lab tutorial it says:

"This transformation is a really important one to understand when using compose. We took a stateful composable, TodoInputItem, and split it into two composables. One with state (TodoItemEntryInput) and one stateless (TodoItemEntry)."

TodoItemEntry should be called -> TodoItemInput

```kotlin
@Composable
fun TodoItemEntryInput(onItemComplete: (TodoItem) -> Unit) {
    // ...
}

@Composable
private fun TodoItemInput(
   text: String,
   onTextChange: (String) -> Unit,
   icon: TodoIcon,
   onIconChange: (TodoIcon) -> Unit,
   submit: () -> Unit,
   iconsVisible: Boolean
) {
    // ...
}
```

I cannot find the website code for it, otherwise I would have created a PR for it.

**Comment by florina-muntenescu** [comment]
Thanks for reporting! Fixed. Will be visible with the alpha10 compose release

**Comment by peterMonteer** [comment]
@florina-muntenescu I think it still needs to change here from TodoItemEntry  to TodoItemInput

![Captura de ecrã 2021-03-06, às 12 08 06](https://user-images.githubusercontent.com/28009502/110206323-d6347400-7e74-11eb-8e86-2a62786d8d77.png)

**Comment by florina-muntenescu** [comment]
Fixed meanwhile
