### ISSUE TITLE
StateCodelab can't remove last character from the TodoInputText

### ISSUE THREAD

**Issue by OscarCreator** [googlecodelabs/android-compose-codelabs#6]
When you have some text in the TextField and then hit delete on the keyboard you are not able to delete the last character. If you click delete when there is one character left, the character stays and the next character you type will be placed to the left of the character left.

Ex:
type: **Hello World**_
delete * 10: **H**_
delete * 1: _**H**
type: **ell**\_**H**

**Comment by florina-muntenescu** [comment]
Tried this with the alpha10 snapshot and an emulator with API 24. Can't reproduce it. 
Is there any other info you can provide?
