### ISSUE TITLE
[StateCodelab] Remove deprecated composables

### ISSUE THREAD

**Issue by nickbutcher** [googlecodelabs/android-compose-codelabs#73]
The state codelab is using deprecated composables such as [LazyColumnFor](https://github.com/googlecodelabs/android-compose-codelabs/search?q=lazycolumnfor), we should update this and perhaps turn on warnings as errors.

**Comment by BertoSerrano** [comment]
This issue should be checked periodically:
- There is a deprecated modifier method in `CraneHome.kt` (`[statusBarsPadding()](https://google.github.io/accompanist/insets/#inset-aware-layouts-insets-ui)`)
- Also, in `MainActivity.kt`, there is a `[ProvideWindowInsets](https://google.github.io/accompanist/insets/#migration-steps)` call with no alternative migration.
- Another call in `ExploreSection.kt` with `[navigationBarsHeight()](https://google.github.io/accompanist/insets/#size-modifiers)`
- and more...
