### ISSUE TITLE
[StateCodelab] The usage of `rememer` in `LazyColumn` in StateCodelab doesn't seem to work or make sense

### ISSUE THREAD

**Issue by ShreckYe** [googlecodelabs/android-compose-codelabs#82]
The usage of `rememer` in `LazyColumn` in StateCodelab doesn't seem to work or make sense to me.

To make the problem more obvious, I made changes to the code in the following way:

First I added 100 items initially in `onCreate`:

```kotlin
for (i in 0 until 100) todoViewModel.addItem(TodoItem(i.toString()))
```

Then I edited the task text to also show the icon alpha in text:

```kotlin
Text(todo.task + " (icon alpha: $iconAlpha)")
```

Now if launch the app, scroll to the bottom of the list and then back to the top, the icon alpha actually changes.

According to the comments on `remember` and `LazyColumn` in the codelab tutorial:

> Remember stores values in the Composition, and will forget them if the composable that called remember is removed.

> It only composes the items currently on the screen, and disposes of them as soon as they leave.

I guess the `TodoRow`s are actually disposed along with its remembered state and then recreated, rather than recomposed, and that's why `remember` doesn't work here.

**Comment by astamato** [comment]
Thank you for flagging this issue! We've replaced the first version of the StateCodelab (Todo app), hence this issue is obsolete.
