### ISSUE TITLE
StateColab imeAction does not add TodoItem

### ISSUE THREAD

**Issue by OscarCreator** [googlecodelabs/android-compose-codelabs#9]
When clicking the imeAction Done on the keyboard the submit callback is run but the text is always blank.

```kotlin
val submit = {
    if (text.isNotBlank()) {
        onItemComplete(TodoItem(text, icon))
        onTextChange("")
        onIconChange(TodoIcon.Default)
    }
}
```

When clicking imeaction Done the statement 
```kotlin
if (text.isNotBlan())
```
is always false, even if there is text in the textfield.

The strange thing is that the TodoEditButton has the exact same callback and it works every time.

**Comment by florina-muntenescu** [comment]
Tried this with an emulator with API 24 and I'm unable to reproduce it. 
Is there any other info you can provide?
